### ISSUE TITLE
Can't change width of bending beam

### ISSUE THREAD

**Issue by ABeer-MHE** [Serince/FEMbyGEN#15]
Hi,

To familiarize myself with this addon I simply tried to change the width of a bending beam, but when I'm at the point 'Generate' -> 'Generate' FreeCAD crashes. If I change the length instead of the width, everything goes fine. I have attached the example.

[bending beam.zip](https://github.com/Serince/FEMbyGEN/files/11285866/bending.beam.zip)

**Comment by Serince** [comment]
Hi,

It is working for me. Maybe before clicking generate button you need to delete earlier generations you created. Please first click delete button which is bottom of the page. In the dev branch, I am preparing a new version which automatically delete earlier created generations when you click generate button.

All the best,
Serdar

**Comment by ABeer-MHE** [comment]
Hello,

Thanks for the fast respond. Everything looks fine now, but I played around with some settings and was able to reproduce the error. 
I created a new file and changed the cube to a part extruded from a sketch. I changed the width, height in the sketch and the length in the extruded body into parameters with 3 levels each. I set up the FEM as before. When I press create to get the generations, FreeCad crashes without any error. If I then reload the file, 'Clear Generations' and press 'Generate' again, it works fine. Maybe you can reproduce this "bug".

Best regards
Andreas
