### ISSUE TITLE
OpenDark / Dark UI visibility problems

### ISSUE THREAD

**Issue by maxwxyz** [Serince/FEMbyGEN#46]
On dark user interfaces, e.g. [OpenDark by @obelisk](https://github.com/obelisk79/OpenDark) some parts are not readable or hard to see:
Icons on the toolbar:
![grafik](https://github.com/Serince/FEMbyGEN/assets/6246609/3f9f9df5-3122-4444-aa5b-4fbf83352697)

Spreadsheet editor:
![grafik](https://github.com/Serince/FEMbyGEN/assets/6246609/45b47b20-01b0-4d1a-ab3e-ac012c4d7cff)

**Comment by Serince** [comment]
Now readability in dark mode is completed. I haven't changed version number, yet. If you want to try, please delete and reinstall
