### ISSUE TITLE
"Initiate" button not working

### ISSUE THREAD

**Issue by jarryidle** [Serince/FEMbyGEN#64]
I just installed FEMbyGEN from the addon manager. when I clicked on the "initiate" button, nothing happened. No parameter spreadsheet was created. The other buttons worked fine though.
My FreeCAD is 0.21.2. The FEMbyGEN version is 2.2.0.

[code]
OS: Windows 11 build 22631
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Assembly4 0.50.15
  * Curves 0.6.44
  * FEMbyGEN 2.2.0
[/code]

**Comment by Serince** [comment]
It was a silly error. I fixed it with a small update.
